apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: us-east-1

iam:
  serviceRoleARN: arn:aws:iam::058264184252:role/eksClusterRole

nodeGroups:
  - name: medium-ng
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
