apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: ap-south-1

nodeGroups:
  - name: t3micro-ng
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
