apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-project
  labels:
    app: go-project
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: go-project
  template:
    metadata:
      labels:
        app: go-project
    spec:
      containers:
      - name: go
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
