name: CICD

on: 
  push:
    branches:
      - main
    paths-ignore:
      -  "README.md"
      - 'helm-chart/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build
        run: |
          go build -o myapp src/main.go
    
  push:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/go-project:${{ github.sha }}
      
  updateHelmTag:
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Helm chart values
        run: |
          sed -i 's/tag:.*/tag: '${{ github.sha }}'/' helm-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --local user.name "akshaysiv"
          git config --local user.email "akshaysiv95@gmail.com"
          git add helm-chart/values.yaml
          git commit -m "Update Helm chart values with new image tag"
          git push origin main
          
          
